### PR TITLE
revised for Bourbon 4.2.3 and Neat 1.7.2

### PR DESCRIPTION
**Pull request by danieljacobarcher**
Revised all auto completions to be in line with the latest Bourbon and Neat versions, haven't looked at the snippets in the docs folder yet.

If it looks good to you, please add it back to Sublime Text Package Control. :+1:

### CODE REVIEW

**Comment by rossedman** [comment]
@danieljacobarcher Looks good! I have actually been using Bourbon & Neat a lot lately so I will go through this and see if everything matches up. What version of Sublime Text are you using? Mainly the reason I deprecated this package is so many people said they couldn't get it installed but I never had any problems.

**Comment by danieljacobarcher** [comment]
@rossedman Thanks :smile:  I'm on Sublime Text 3, latest build, and had no problem installing. When I first installed your version last year, I did it via Package Control. I wonder if their installation issues were based on the install instructions - which would vary if Package Control is installed on their machines. To get this to install for me, I had to place it in the Package Control folder, have Package Control build it as a sublime-package, put that with the other packages, and whitelist it in Package Control User settings.

**Comment by rossedman** [comment]
@danieljacobarcher Hmmm. Yeah, it is pretty easy to custom install but need to get it updated in Package Control. The other thing I haven't been able to solve which I need to dig into is allowing auto completions to have multiple sources. For insance, this package currently only works if your syntax is set to SASS but does not work if your syntax is set to SCSS.

**Comment by rossedman** [comment]
@danieljacobarcher Might have found my [answer](https://www.sublimetext.com/forum/viewtopic.php?f=2&t=4923). I may update all of this too and see if we can get it working in multiple contexts.

**Comment by danieljacobarcher** [comment]
@rossedman Nice! I look forward to it.

**Comment by rossedman** [comment]
@danieljacobarcher Thanks a lot. I appreciate the PR. I will update the docs and give you credit too. You brought it back to life man. I had moved to other things but for the past few months have been using Bourbon and Neat again and it was on my mind.

**Comment by danieljacobarcher** [comment]
@rossedman No worries- my pleasure. I really got into using Bourbon, Neat, and Bitters in the app I've been building since Sept, and I recently had to restore my laptop and was sad when I couldn't find Derby to install. It's become second-nature to me in coding and saves me loads of time. I can't imagine writing all those includes without it.

**Comment by rossedman** [comment]
@danieljacobarcher Glad it helped. I love productivity tools. Life would be hard without them. Haha. I know Bourbon 5.0 is in the works. Will try to keep it updated for that too.

**Comment by rossedman** [comment]
@danieljacobarcher Cleaned everything up and resubmitted to Package Control! Thanks again.

**Pull request merged**
